plugins { id 'com.android.application' }

android {
    namespace 'com.omegaplus.proai'
    compileSdk 36
    buildFeatures {
        buildConfig true
    }
    defaultConfig {
        applicationId 'com.omegaplus.proai'
        minSdk 23
        targetSdk 36
        versionCode 6
        versionName '1.5.6'
    }
}
